
import "../globals.css";
import { Inter } from "next/font/google";
import React from "react";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <html lang='en'>
        <body className={`${inter.className} bg-dark-1`}>{children}</body>
  </html>
  )
}
